# Generated by Django 2.2.7 on 2019-12-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management', '0002_auto_20191210_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'verbose_name': 'Email Log', 'verbose_name_plural': 'Email Logs'},
        ),
    ]
