# Generated by Django 3.2.8 on 2022-01-24 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log_management', '0003_auto_20191220_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=300, unique=True, verbose_name='Session key')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='Additional data')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
            },
        ),
    ]
