# Generated by Django 3.2.8 on 2022-01-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management', '0004_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='session_key',
            field=models.CharField(max_length=300, verbose_name='Session key'),
        ),
    ]
