# Generated by Django 5.2.12 on 2026-04-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management', '0005_alter_actionlog_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='categories',
            field=models.JSONField(default="[\"cookies-performance\"]", verbose_name='Categories'),
            preserve_default=False,
        ),
    ]
