# Generated by Django 2.0.2 on 2018-06-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='exclusive_memberships',
            field=models.ManyToManyField(blank=True, related_name='packages', to='store.Membership', verbose_name='Memberships'),
        ),
    ]
