# Generated by Django 2.0.2 on 2018-07-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_package_exclusive_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Available'),
            preserve_default=False,
        ),
    ]
