# Generated by Django 2.0.2 on 2018-08-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_membership_many_academic_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='authorization_id',
            field=models.CharField(default=12, max_length=253, verbose_name='Authorization ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_id',
            field=models.CharField(default=12, max_length=253, verbose_name='Settlement ID'),
            preserve_default=False,
        ),
    ]
