# Generated by Django 2.0.2 on 2018-08-15 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, verbose_name='Name')),
                ('external_api_id', models.CharField(max_length=253, verbose_name='External profile ID')),
                ('external_api_url', models.CharField(max_length=253, verbose_name='External profile url')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profiles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment profile',
                'verbose_name_plural': 'Payment profiles',
            },
        ),
    ]
