# Generated by Django 2.0.2 on 2018-10-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_historicalmembership_historicalorder_historicalorderline_historicalpackage_hist'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembership',
            name='details_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='details_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='name_en',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='name_fr',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalpackage',
            name='details_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='historicalpackage',
            name='details_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='historicalpackage',
            name='name_en',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalpackage',
            name='name_fr',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='membership',
            name='details_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='membership',
            name='details_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='membership',
            name='name_en',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='membership',
            name='name_fr',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='package',
            name='details_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='package',
            name='details_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='package',
            name='name_en',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='package',
            name='name_fr',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
    ]
