# Generated by Django 2.0.8 on 2018-11-21 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_model_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('details', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Details')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction date')),
                ('authorization_id', models.CharField(max_length=253, verbose_name='Authorization ID')),
                ('settlement_id', models.CharField(max_length=253, verbose_name='Settlement ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_payments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Custom payment',
                'verbose_name_plural': 'Custom payments',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomPayment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=253, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('details', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Details')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction date')),
                ('authorization_id', models.CharField(max_length=253, verbose_name='Authorization ID')),
                ('settlement_id', models.CharField(max_length=253, verbose_name='Settlement ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Custom payment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
