# Generated by Django 2.0.8 on 2018-12-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_custompayment_historicalcustompayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Reference number'),
        ),
        migrations.AddField(
            model_name='historicalcustompayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Reference number'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='reference_number',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Reference number'),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Reference number'),
        ),
    ]
