# Generated by Django 2.0.8 on 2019-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0005_retirement_place_name'),
        ('workplace', '0021_workplace_place_name'),
        ('store', '0012_coupon_couponuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_memberships',
            field=models.ManyToManyField(related_name='applicable_coupons', to='store.Membership', verbose_name='Applicable memberships'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_packages',
            field=models.ManyToManyField(related_name='applicable_coupons', to='store.Package', verbose_name='Applicable packages'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_retirements',
            field=models.ManyToManyField(related_name='applicable_coupons', to='retirement.Retirement', verbose_name='Applicable retirements'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_timeslots',
            field=models.ManyToManyField(related_name='applicable_coupons', to='workplace.TimeSlot', verbose_name='Applicable timeslots'),
        ),
    ]
