# Generated by Django 2.0.8 on 2019-01-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_applicable_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='applicable_memberships',
            field=models.ManyToManyField(blank=True, related_name='applicable_coupons', to='store.Membership', verbose_name='Applicable memberships'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_packages',
            field=models.ManyToManyField(blank=True, related_name='applicable_coupons', to='store.Package', verbose_name='Applicable packages'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_product_types',
            field=models.ManyToManyField(blank=True, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_retirements',
            field=models.ManyToManyField(blank=True, related_name='applicable_coupons', to='retirement.Retirement', verbose_name='Applicable retirements'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_timeslots',
            field=models.ManyToManyField(blank=True, related_name='applicable_coupons', to='workplace.TimeSlot', verbose_name='Applicable timeslots'),
        ),
    ]
