# Generated by Django 2.0.8 on 2019-01-23 16:11

from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_coupon_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderline',
            name='coupon',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.Coupon'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='store.Coupon', verbose_name='Applied coupon'),
        ),
        migrations.AddField(
            model_name='historicalorderline',
            name='coupon_real_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, default=0, verbose_name='Coupon real value'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='coupon_real_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, default=0, verbose_name='Coupon real value'),
        ),
        migrations.AddField(
            model_name='historicalorderline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Orderline cost'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Orderline cost'),
        ),
    ]
