# Generated by Django 2.0.8 on 2019-01-23 16:11

from django.db import migrations, models
import django.db.models.deletion


def move_coupon_to_orderlines(apps, schema_editor):
    '''
    We can't import the Order model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Order = apps.get_model('store', 'Order')
    Retirement = apps.get_model('retirement', 'Retirement')
    for order in Order.objects.all():
        if order.coupon:
            retirement_orderlines = order.order_lines.filter(
                content_type__model='retirement'
            )

            retirements_id = retirement_orderlines.values_list('object_id', flat=True)

            applicable_retirement = Retirement.objects.filter(
                id__in=retirements_id
            ).latest('price')

            applicable_orderline = retirement_orderlines.get(
                object_id=applicable_retirement.pk
            )
            applicable_orderline.coupon = order.coupon
            applicable_orderline.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_coupon_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderline',
            name='coupon',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.Coupon'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='store.Coupon', verbose_name='Applied coupon'),
        ),
        migrations.AddField(
            model_name='historicalorderline',
            name='coupon_real_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Coupon real value'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='coupon_real_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Coupon real value'),
        ),
        migrations.RunPython(move_coupon_to_orderlines, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='historicalorder',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
