# Generated by Django 2.0.8 on 2019-01-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrefund',
            name='refund_id',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Refund ID'),
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_id',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Refund ID'),
        ),
    ]
