# Generated by Django 2.0.8 on 2019-02-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_refund_refund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='percent_off',
            field=models.PositiveIntegerField(null=True, verbose_name='Percentage off'),
        ),
        migrations.AddField(
            model_name='historicalcoupon',
            name='percent_off',
            field=models.PositiveIntegerField(null=True, verbose_name='Percentage off'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Value'),
        ),
    ]
