# Generated by Django 2.2.2 on 2019-06-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0013_auto_20190529_1412'),
        ('store', '0025_historicalmembershipcoupon_membershipcoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_retirements',
        ),
        migrations.RemoveField(
            model_name='membershipcoupon',
            name='applicable_retirements',
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_retreats',
            field=models.ManyToManyField(blank=True, related_name='applicable_coupons', to='retirement.Retreat', verbose_name='Applicable retreats'),
        ),
        migrations.AddField(
            model_name='membershipcoupon',
            name='applicable_retreats',
            field=models.ManyToManyField(blank=True, related_name='applicable_membershipcoupons', to='retirement.Retreat', verbose_name='Applicable retreats'),
        ),
    ]
