# Generated by Django 2.2.2 on 2019-08-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20190603_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, verbose_name='Name')),
                ('available', models.BooleanField(default=False, verbose_name='Available')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('details', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details')),
                ('max_quantity', models.IntegerField(default=0, verbose_name='Max Quantity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='historicalmembership',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='package',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
    ]
