# Generated by Django 2.2.2 on 2019-08-16 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0028_auto_20190815_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='available_on_product_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='contenttypes.ContentType', verbose_name='Applicable product types'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='available_on_products',
            field=models.ManyToManyField(blank=True, related_name='option_products', to='store.BaseProduct', verbose_name='Applicable products'),
        ),
        migrations.CreateModel(
            name='HistoricalOptionProduct',
            fields=[
                ('baseproduct_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='store.BaseProduct')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=253, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=253, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=253, null=True, verbose_name='Name')),
                ('available', models.BooleanField(default=False, verbose_name='Available')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('details', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details')),
                ('details_fr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details')),
                ('details_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details')),
                ('max_quantity', models.IntegerField(default=0, verbose_name='Max Quantity')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical option product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
