# Generated by Django 2.2.2 on 2019-09-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20190819_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderline',
            name='metadata',
            field=models.TextField(blank=True, null=True, verbose_name='Metada'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='metadata',
            field=models.TextField(blank=True, null=True, verbose_name='Metada'),
        ),
    ]
