# Generated by Django 2.2.6 on 2019-11-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20190901_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percent_off',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Percentage off'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='percent_off',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Percentage off'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='historicalmembership',
            name='old_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id before migrate to base product'),
        ),
        migrations.AlterField(
            model_name='historicalmembershipcoupon',
            name='percent_off',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Percentage off'),
        ),
        migrations.AlterField(
            model_name='historicalmembershipcoupon',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='old_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id before migrate to base product'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='old_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id before migrate to base product'),
        ),
        migrations.AlterField(
            model_name='membershipcoupon',
            name='percent_off',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Percentage off'),
        ),
        migrations.AlterField(
            model_name='membershipcoupon',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='package',
            name='old_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id before migrate to base product'),
        ),
    ]
