# Generated by Django 2.2.12 on 2020-05-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20191112_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_applicable_to_physical_retreat',
            field=models.BooleanField(default=False, verbose_name='Applicable to physical retreat'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_applicable_to_virtual_retreat',
            field=models.BooleanField(default=False, verbose_name='Applicable to virtual retreat'),
        ),
        migrations.AddField(
            model_name='historicalcoupon',
            name='is_applicable_to_physical_retreat',
            field=models.BooleanField(default=False, verbose_name='Applicable to physical retreat'),
        ),
        migrations.AddField(
            model_name='historicalcoupon',
            name='is_applicable_to_virtual_retreat',
            field=models.BooleanField(default=False, verbose_name='Applicable to virtual retreat'),
        ),
        migrations.AddField(
            model_name='historicalmembershipcoupon',
            name='is_applicable_to_physical_retreat',
            field=models.BooleanField(default=False, verbose_name='Applicable to physical retreat'),
        ),
        migrations.AddField(
            model_name='historicalmembershipcoupon',
            name='is_applicable_to_virtual_retreat',
            field=models.BooleanField(default=False, verbose_name='Applicable to virtual retreat'),
        ),
        migrations.AddField(
            model_name='membershipcoupon',
            name='is_applicable_to_physical_retreat',
            field=models.BooleanField(default=False, verbose_name='Applicable to physical retreat'),
        ),
        migrations.AddField(
            model_name='membershipcoupon',
            name='is_applicable_to_virtual_retreat',
            field=models.BooleanField(default=False, verbose_name='Applicable to virtual retreat'),
        ),
    ]
