# Generated by Django 2.2.13 on 2021-04-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20200525_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembership',
            name='welcome_email_template_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Welcome email template ID'),
        ),
        migrations.AddField(
            model_name='membership',
            name='welcome_email_template_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Welcome email template ID'),
        ),
    ]
