# Generated by Django 2.2.13 on 2021-08-22 19:04

from django.db import migrations


def migrate_membership_plan(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Membership = apps.get_model('store', 'Membership')
    User = apps.get_model('blitz_api', 'User')

    queryset = Membership.objects.filter(old_id=2)
    if queryset.count():
        diplomed = queryset[0]
    else:
        diplomed = None

    for membership in Membership.objects.all():
        if membership.old_id == 2:
            membership.name_fr = 'DIPLÔMÉ.E'
            membership.save()

        if membership.old_id == 3:
            if diplomed:
                # if we have the membership Diplomed
                # we transfer users from Allied to Diplomed before removing Allied
                for user in User.objects.filter(membership=membership):
                    user.membership = diplomed
                    user.save()

            membership.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20210430_1132'),
    ]

    operations = [
        migrations.RunPython(migrate_membership_plan),
    ]
