# Generated by Django 2.2.13 on 2021-08-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20210822_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembership',
            name='picture',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='picture'),
        ),
        migrations.AddField(
            model_name='membership',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='memberships', verbose_name='picture'),
        ),
    ]
