# Generated by Django 2.2.13 on 2021-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20210823_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('price',), 'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('price',), 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AddField(
            model_name='historicalpackage',
            name='picture',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='picture'),
        ),
        migrations.AddField(
            model_name='package',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='packages', verbose_name='picture'),
        ),
    ]
