# Generated by Django 3.2.8 on 2022-08-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20210827_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloptionproduct',
            name='has_stock',
            field=models.BooleanField(default=False, help_text='True if option has stock, False if stock is infinite or NA', verbose_name='Has stock'),
        ),
        migrations.AddField(
            model_name='historicaloptionproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Maximum quantity available for this option', verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='has_stock',
            field=models.BooleanField(default=False, help_text='True if option has stock, False if stock is infinite or NA', verbose_name='Has stock'),
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Maximum quantity available for this option', verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='orderlinebaseproduct',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='historicaloptionproduct',
            name='max_quantity',
            field=models.IntegerField(default=0, help_text='Maximum allowed quantity per orderline', verbose_name='Max Quantity'),
        ),
        migrations.AlterField(
            model_name='optionproduct',
            name='max_quantity',
            field=models.IntegerField(default=0, help_text='Maximum allowed quantity per orderline', verbose_name='Max Quantity'),
        ),
    ]
