# Generated by Django 3.2.8 on 2022-08-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20220809_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloptionproduct',
            name='type',
            field=models.CharField(choices=[('common', 'Common'), ('shared_room', 'Shared room')], default='common', max_length=100),
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='type',
            field=models.CharField(choices=[('common', 'Common'), ('shared_room', 'Shared room')], default='common', max_length=100),
        ),
    ]
