# Generated by Django 3.2.8 on 2022-08-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20220804_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlinebaseproduct',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Quantity'),
        ),
    ]
