# Generated by Django 3.2.8 on 2022-08-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20220816_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloptionproduct',
            name='has_stock',
        ),
        migrations.RemoveField(
            model_name='optionproduct',
            name='has_stock',
        ),
        migrations.AddField(
            model_name='historicaloptionproduct',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0, help_text='Initial stock for this option', verbose_name='Initial stock'),
        ),
        migrations.AddField(
            model_name='historicaloptionproduct',
            name='manage_stock',
            field=models.BooleanField(default=False, help_text='True if option manage stock, False if stock is infinite or NA', verbose_name='Manage stock'),
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0, help_text='Initial stock for this option', verbose_name='Initial stock'),
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='manage_stock',
            field=models.BooleanField(default=False, help_text='True if option manage stock, False if stock is infinite or NA', verbose_name='Manage stock'),
        ),
        migrations.AlterField(
            model_name='historicaloptionproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Current quantity available for this option', verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='optionproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Current quantity available for this option', verbose_name='Stock'),
        ),
    ]
