# Generated by Django 3.2.8 on 2022-08-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20220816_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloptionproduct',
            name='has_stock',
        ),
        migrations.RemoveField(
            model_name='optionproduct',
            name='has_stock',
        ),
        migrations.AddField(
            model_name='historicaloptionproduct',
            name='manage_stock',
            field=models.BooleanField(default=False, help_text='True if option manage stock, False if stock is infinite or NA', verbose_name='Manage stock'),
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='manage_stock',
            field=models.BooleanField(default=False, help_text='True if option manage stock, False if stock is infinite or NA', verbose_name='Manage stock'),
        ),
    ]
