# Generated by Django 3.2.8 on 2022-08-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_auto_20220817_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloptionproduct',
            name='is_room_option',
            field=models.BooleanField(default=False, verbose_name='Determine if this option can be considered as a room option'),
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='is_room_option',
            field=models.BooleanField(default=False, verbose_name='Determine if this option can be considered as a room option'),
        ),
        migrations.AlterField(
            model_name='historicaloptionproduct',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('shared_room', 'Shared room')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='optionproduct',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('shared_room', 'Shared room')], default='none', max_length=100),
        ),
    ]
