# Generated by Django 3.2.8 on 2022-08-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_orderlinebaseproduct_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlinebaseproduct',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadata'),
        ),
    ]
