# Generated by Django 3.2.8 on 2022-10-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0062_auto_20220821_1243'),
        ('store', '0042_auto_20220821_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='available_on_retreat_types',
            field=models.ManyToManyField(blank=True, related_name='option_retreat_types', to='retirement.RetreatType', verbose_name='Applicable retreat types'),
        ),
    ]
