# Generated by Django 3.2.8 on 2022-10-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0062_auto_20220821_1243'),
        ('store', '0043_baseproduct_available_on_retreat_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_retreat_types',
            field=models.ManyToManyField(blank=True, related_name='applicable_coupons', to='retirement.RetreatType', verbose_name='Applicable retreat types'),
        ),
        migrations.AddField(
            model_name='membershipcoupon',
            name='applicable_retreat_types',
            field=models.ManyToManyField(blank=True, related_name='applicable_membershipcoupons', to='retirement.RetreatType', verbose_name='Applicable retreat types'),
        ),
    ]
