# Generated by Django 3.2.8 on 2022-12-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20221214_1614'),
    ]

    operations = [
    ]
