# Generated by Django 4.2.5 on 2023-11-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0065_historicalreservation_deleted_by_cascade_and_more'),
        ('workplace', '0028_historicalperiod_deleted_by_cascade_and_more'),
        ('store', '0048_autopopulate_orderline_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='couponuser',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='historicalcoupon',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='historicalcouponuser',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='historicalmembershipcoupon',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='historicalrefund',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='membershipcoupon',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='refund',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_memberships',
            field=models.ManyToManyField(blank=True, related_name='applicable_%(class)ss', to='store.membership', verbose_name='Applicable memberships'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_packages',
            field=models.ManyToManyField(blank=True, related_name='applicable_%(class)ss', to='store.package', verbose_name='Applicable packages'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_retreat_types',
            field=models.ManyToManyField(blank=True, related_name='applicable_%(class)ss', to='retirement.retreattype', verbose_name='Applicable retreat types'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_retreats',
            field=models.ManyToManyField(blank=True, related_name='applicable_%(class)ss', to='retirement.retreat', verbose_name='Applicable retreats'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_timeslots',
            field=models.ManyToManyField(blank=True, related_name='applicable_%(class)ss', to='workplace.timeslot', verbose_name='Applicable timeslots'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='couponuser',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcouponuser',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmembershipcoupon',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrefund',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='membershipcoupon',
            name='applicable_memberships',
            field=models.ManyToManyField(blank=True, related_name='applicable_%(class)ss', to='store.membership', verbose_name='Applicable memberships'),
        ),
        migrations.AlterField(
            model_name='membershipcoupon',
            name='applicable_packages',
            field=models.ManyToManyField(blank=True, related_name='applicable_%(class)ss', to='store.package', verbose_name='Applicable packages'),
        ),
        migrations.AlterField(
            model_name='membershipcoupon',
            name='applicable_retreat_types',
            field=models.ManyToManyField(blank=True, related_name='applicable_%(class)ss', to='retirement.retreattype', verbose_name='Applicable retreat types'),
        ),
        migrations.AlterField(
            model_name='membershipcoupon',
            name='applicable_retreats',
            field=models.ManyToManyField(blank=True, related_name='applicable_%(class)ss', to='retirement.retreat', verbose_name='Applicable retreats'),
        ),
        migrations.AlterField(
            model_name='membershipcoupon',
            name='applicable_timeslots',
            field=models.ManyToManyField(blank=True, related_name='applicable_%(class)ss', to='workplace.timeslot', verbose_name='Applicable timeslots'),
        ),
        migrations.AlterField(
            model_name='membershipcoupon',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
