# Generated by Django 5.2.12 on 2026-04-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_coupon_affiliation_historicalcoupon_affiliation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbaseproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical base product', 'verbose_name_plural': 'historical base products'},
        ),
        migrations.AlterModelOptions(
            name='historicalcoupon',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical coupon', 'verbose_name_plural': 'historical coupons'},
        ),
        migrations.AlterModelOptions(
            name='historicalcouponuser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical coupon user', 'verbose_name_plural': 'historical coupon users'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustompayment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Custom payment', 'verbose_name_plural': 'historical Custom payments'},
        ),
        migrations.AlterModelOptions(
            name='historicalmembership',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Membership', 'verbose_name_plural': 'historical Memberships'},
        ),
        migrations.AlterModelOptions(
            name='historicalmembershipcoupon',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical membership coupon', 'verbose_name_plural': 'historical membership coupons'},
        ),
        migrations.AlterModelOptions(
            name='historicaloptionproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical option product', 'verbose_name_plural': 'historical option products'},
        ),
        migrations.AlterModelOptions(
            name='historicalorder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Order', 'verbose_name_plural': 'historical Orders'},
        ),
        migrations.AlterModelOptions(
            name='historicalorderline',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Order line', 'verbose_name_plural': 'historical Order lines'},
        ),
        migrations.AlterModelOptions(
            name='historicalpackage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Package', 'verbose_name_plural': 'historical Packages'},
        ),
        migrations.AlterModelOptions(
            name='historicalpaymentprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Payment profile', 'verbose_name_plural': 'historical Payment profiles'},
        ),
        migrations.AlterModelOptions(
            name='historicalrefund',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Refund', 'verbose_name_plural': 'historical Refunds'},
        ),
        migrations.AlterField(
            model_name='historicalbaseproduct',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcouponuser',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcustompayment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmembership',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmembershipcoupon',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaloptionproduct',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalorderline',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpaymentprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrefund',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
