# Generated by Django 5.2.13 on 2026-05-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_historicalbaseproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction date')),
                ('transaction_id', models.CharField(blank=True, max_length=253, null=True, verbose_name='Refund ID')),
                ('is_successful', models.BooleanField(verbose_name='Is successful')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.refund', verbose_name='Refund')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
