# Generated by Django 5.2.13 on 2026-05-06 15:35

from django.db import migrations

def populate_refund_transaction(apps, schema_editor):
    from django.contrib.contenttypes.models import ContentType
    Refund = apps.get_model('store', 'Refund')
    RefundTransaction = apps.get_model('store', 'RefundTransaction')

    refunds = Refund.objects.all()
    for refund in refunds:
        RefundTransaction.objects.create(
            refund=refund,
            amount=refund.amount,
            transaction_date=refund.refund_date,
            transaction_id=refund.refund_id,
            is_successful=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_refundtransaction'),
    ]

    operations = [
        migrations.RunPython(populate_refund_transaction),
    ]
