# Generated by Django 5.2.13 on 2026-05-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_auto_20260506_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrefund',
            name='refund_id',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='refund_id',
        ),
        migrations.AddField(
            model_name='refundtransaction',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
    ]
