language: python

python:
  - 3.6

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pycodestyle

script:
  - coverage run --omit=*.virtualenvs*,*virtualenv*,*__init__*,*migrations/* manage.py test .
  - pycodestyle --count --show-source --exclude=migrations,.*,__pycache__,docs,env  .

after_success:
  coveralls
