version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blitz
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./.env.docker
    command: /start
    volumes:
      - .:/opt/project
      - /opt/project/src
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db:
