version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: blitz
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d blitz"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s

  api:
    restart: always
    build:
      context: .
    env_file: .env.docker
    volumes:
      - .:/opt/project
      - /opt/project/src
    command: /start
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000

  documentation:
      restart: always
      build: ./
      command: "mkdocs serve"
      volumes:
        - .:/opt/project
      ports:
        - "8001:8001"

volumes:
  db:
