# Generated by Django 2.0.2 on 2018-04-30 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0003_auto_20180419_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('type', models.CharField(choices=[('account_activation', 'Account activation'), ('password_change', 'Password change')], max_length=100, verbose_name='Type of action')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('expires', models.DateTimeField(blank=True, verbose_name='Expiration date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='temporarytoken',
            options={'verbose_name': 'Temporary token', 'verbose_name_plural': 'Temporary tokens'},
        ),
    ]
