# Generated by Django 2.0.2 on 2018-05-10 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0006_academic_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blitz_api.AcademicField', verbose_name='Academic field'),
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blitz_api.AcademicLevel', verbose_name='Academic level'),
        ),
    ]
