# Generated by Django 2.0.2 on 2018-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0007_user_academic_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='example',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Email example'),
        ),
    ]
