# Generated by Django 2.0.2 on 2018-06-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_package_exclusive_memberships'),
        ('blitz_api', '0008_domain_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Membership', verbose_name='Membership'),
        ),
    ]
