# Generated by Django 2.0.2 on 2018-06-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0010_user_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_end',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Membership end date'),
        ),
    ]
