# Generated by Django 2.0.2 on 2018-06-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0011_user_membership_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reservations',
        ),
        migrations.AddField(
            model_name='user',
            name='tickets',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tickets'),
        ),
    ]
