# Generated by Django 2.0.8 on 2018-12-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0014_model_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='personnal_restrictions',
            field=models.TextField(blank=True, null=True, verbose_name='Personnal restrictions'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='personnal_restrictions',
            field=models.TextField(blank=True, null=True, verbose_name='Personnal restrictions'),
        ),
    ]
