# Generated by Django 2.0.8 on 2019-01-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0015_user_city_and_personnal_restrictions_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='academic_program_code',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Academic program code'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='student_number',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Student number'),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_program_code',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Academic program code'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Student number'),
        ),
    ]
