# Generated by Django 2.0.8 on 2019-05-13 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0017_actiontoken_data_change_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
            ],
        ),
    ]
