# Generated by Django 2.0.8 on 2019-05-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0018_auto_20190517_1435'),
        ('blitz_api', '0018_auto_20190513_1444'),
    ]

    operations = [
    ]
