# Generated by Django 2.0.8 on 2019-05-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0019_merge_20190524_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportmedia',
            name='file',
            field=models.FileField(upload_to='export/%Y/%m/', verbose_name='file'),
        ),
    ]
