# Generated by Django 2.2.6 on 2019-10-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0020_auto_20190529_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], max_length=100, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], max_length=100, null=True, verbose_name='Language'),
        ),
    ]
