# Generated by Django 2.2.10 on 2020-04-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0021_auto_20191010_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='hide_newsletter',
            field=models.BooleanField(default=False, verbose_name='Hide newsletter'),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_newsletter',
            field=models.BooleanField(default=False, verbose_name='Hide newsletter'),
        ),
    ]
