# Generated by Django 3.2.8 on 2022-01-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0024_auto_20201125_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
