# Generated by Django 3.2.8 on 2022-02-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0025_auto_20220124_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='last_acceptation_terms_and_conditions',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last acceptation of the terms and conditions'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_acceptation_terms_and_conditions',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last acceptation of the terms and conditions'),
        ),
    ]
