# Generated by Django 3.2.8 on 2022-09-02 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0026_auto_20220208_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportmedia',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='exportmedia',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='exportmedia',
            name='type',
            field=models.CharField(choices=[('ANONYMOUS CHRONO', 'Anonymous Chrono'), ('OTHER', 'Other'), ('RETREAT SALES', 'Retreat sales'), ('RETREAT PARTICIPATION', 'Retreat participation'), ('RETREAT OPTIONS', 'Retreat options')], default='OTHER', max_length=255),
        ),
    ]
