# Generated by Django 3.2.8 on 2022-11-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0027_auto_20220902_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportmedia',
            name='type',
            field=models.CharField(choices=[('ANONYMOUS CHRONO DATA', 'Anonymous Chrono data'), ('OTHER', 'Other'), ('RETREAT SALES', 'Retreat sales'), ('RETREAT PARTICIPATION', 'Retreat participation'), ('RETREAT OPTIONS', 'Retreat options'), ('RETREAT ROOM DISTRIBUTION', 'Retreat room distribution')], default='OTHER', max_length=255),
        ),
    ]
