# Generated by Django 3.2.8 on 2023-02-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0028_alter_exportmedia_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='_tomato_field_matrix',
            field=models.TextField(blank=True, null=True, verbose_name='Tomato field matrix'),
        ),
        migrations.AddField(
            model_name='user',
            name='_tomato_field_matrix',
            field=models.TextField(blank=True, null=True, verbose_name='Tomato field matrix'),
        ),
        migrations.AlterField(
            model_name='exportmedia',
            name='type',
            field=models.CharField(choices=[('ANONYMOUS CHRONO DATA', 'Anonymous Chrono data'), ('OTHER', 'Other'), ('RETREAT SALES', 'Retreat sales'), ('RETREAT PARTICIPATION', 'Retreat participation'), ('RETREAT OPTIONS', 'Retreat options')], default='OTHER', max_length=255),
        ),
    ]
