# Generated by Django 3.2.8 on 2023-06-27 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0029_auto_20230203_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_link', models.TextField(verbose_name='Full link')),
                ('type', models.CharField(choices=[('DOWNLOAD', 'Download')], default='DOWNLOAD', max_length=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('nb_uses', models.PositiveIntegerField(default=0, verbose_name='Number of uses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.AlterField(
            model_name='exportmedia',
            name='type',
            field=models.CharField(choices=[('ANONYMOUS CHRONO DATA', 'Anonymous Chrono data'), ('OTHER', 'Other'), ('RETREAT SALES', 'Retreat sales'), ('RETREAT PARTICIPATION', 'Retreat participation'), ('RETREAT OPTIONS', 'Retreat options'), ('COUPON USAGE', 'Coupon usage')], default='OTHER', max_length=255),
        ),
    ]
