# Generated by Django 4.2.5 on 2024-04-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0030_auto_20230627_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportmedia',
            name='type',
            field=models.CharField(choices=[('ANONYMOUS CHRONO DATA', 'Anonymous Chrono data'), ('OTHER', 'Other'), ('RETREAT SALES', 'Retreat sales'), ('RETREAT PARTICIPATION', 'Retreat participation'), ('RETREAT OPTIONS', 'Retreat options'), ('COUPON USAGE', 'Coupon usage'), ('SALES AND REFUND', 'Sales and refund')], default='OTHER', max_length=255),
        ),
    ]
