# Generated by Django 4.2.5 on 2025-11-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0032_historicalaffiliation_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='affiliation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blitz_api.affiliation', verbose_name='Affiliation'),
        ),
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blitz_api.affiliation', verbose_name='Affiliation'),
        ),
    ]
