# Generated by Django 4.2.5 on 2025-12-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0033_historicaluser_affiliation_user_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='last_inactivity_alert_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last inactivity alert sent'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_inactivity_alert_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last inactivity alert sent'),
        ),
        migrations.AlterField(
            model_name='exportmedia',
            name='type',
            field=models.CharField(choices=[('ANONYMOUS CHRONO DATA', 'Anonymous Chrono data'), ('OTHER', 'Other'), ('RETREAT SALES', 'Retreat sales'), ('RETREAT PARTICIPATION', 'Retreat participation'), ('RETREAT OPTIONS', 'Retreat options'), ('COUPON USAGE', 'Coupon usage'), ('SALES AND REFUND', 'Sales and refund'), ('PERSONAL DATA', 'Personal data')], default='OTHER', max_length=255),
        ),
    ]
