# Generated by Django 4.2.5 on 2026-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_api', '0034_historicaluser_last_inactivity_alert_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='anonymisation_date',
            field=models.DateTimeField(blank=True, help_text='Date when the user account had been anonymised', null=True, verbose_name='Anonymisation date'),
        ),
        migrations.AddField(
            model_name='user',
            name='anonymisation_date',
            field=models.DateTimeField(blank=True, help_text='Date when the user account had been anonymised', null=True, verbose_name='Anonymisation date'),
        ),
    ]
