# Generated by Django 3.2.8 on 2021-11-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0003_auto_20211105_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
