# Generated by Django 3.2.8 on 2022-01-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0005_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Longitude'),
        ),
    ]
