# Generated by Django 3.2.8 on 2022-01-24 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tomato', '0006_auto_20220119_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tomato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tomato', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Number of tomato')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomatoes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
