# Generated by Django 3.2.8 on 2023-01-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tomato', '0007_tomato'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomato',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='tomato',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tomato',
            name='source',
            field=models.CharField(choices=[('RETREAT', 'Retreat'), ('TIMESLOT', 'Timeslot'), ('CHRONO', 'Chrono'), ('USER', 'User')], default='CHRONO', max_length=255),
        ),
    ]
