# Generated by Django 3.2.8 on 2023-01-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0008_auto_20230110_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomato',
            name='source',
            field=models.CharField(choices=[('RETREAT', 'Retreat'), ('TIMESLOT', 'Timeslot'), ('CHRONO', 'Chrono'), ('USER', 'User')], max_length=255),
        ),
    ]
