# Generated by Django 2.2.8 on 2020-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CKEditorPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Key')),
                ('data', models.TextField(blank=True, verbose_name='Data')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
    ]
