# Generated by Django 2.0.2 on 2018-05-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('location', '0002_auto_20171230_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, verbose_name='Name')),
                ('details', models.CharField(max_length=1000, verbose_name='Details')),
                ('seats', models.IntegerField(verbose_name='Seats')),
                # ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='location.Address')),
            ],
            options={
                'verbose_name': 'Workplace',
                'verbose_name_plural': 'Workplaces',
            },
        ),
    ]
