# Generated by Django 2.0.2 on 2018-05-26 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0003_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, verbose_name='Name')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='workplace.Period', verbose_name='Period')),
            ],
            options={
                'verbose_name': 'Time slot',
                'verbose_name_plural': 'Time slots',
            },
        ),
    ]
