# Generated by Django 2.0.2 on 2018-05-27 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workplace', '0004_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='time_slots', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
