# Generated by Django 2.0.2 on 2018-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0005_timeslot_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price'),
        ),
    ]
