# Generated by Django 2.0.2 on 2018-06-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0006_price_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
    ]
