# Generated by Django 2.0.2 on 2018-06-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0006_price_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='name',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Name'),
        ),
    ]
