# Generated by Django 2.0.2 on 2018-06-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0008_timeslot_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='timezone',
            field=models.CharField(default='America/Montreal', max_length=100, verbose_name='Timezone'),
            preserve_default=False,
        ),
    ]
