# Generated by Django 2.0.2 on 2018-06-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0009_workplace_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='address_line1',
            field=models.CharField(default='random address', max_length=45, verbose_name='Address line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='city',
            field=models.CharField(default='random city', max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='country',
            field=models.CharField(default='random country', max_length=45, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='postal_code',
            field=models.CharField(default='HOH OHO', max_length=10, verbose_name='Postal code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='state_province',
            field=models.CharField(default='random state', max_length=55, verbose_name='State/Province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplace',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Timezone'),
        ),
    ]
