# Generated by Django 2.0.2 on 2018-06-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0011_auto_20180624_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='users',
        ),
    ]
