# Generated by Django 2.0.2 on 2018-06-24 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workplace', '0012_remove_timeslot_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='users1',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='time_slots', through='workplace.Reservation', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
