# Generated by Django 2.0.2 on 2018-07-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0013_auto_20180624_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='address_line2',
            field=models.CharField(max_length=45, null=True, verbose_name='Address line 2'),
        ),
    ]
