# Generated by Django 2.0.2 on 2018-10-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0015_historicalperiod_historicalpicture_historicalreservation_historicaltimeslot_historicalworkplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkplace',
            name='address_line2',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='address_line2',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 2'),
        ),
    ]
