# Generated by Django 2.0.2 on 2018-10-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0018_enable_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperiod',
            name='name_en',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalperiod',
            name='name_fr',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalpicture',
            name='name_en',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalpicture',
            name='name_fr',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicaltimeslot',
            name='name_en',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicaltimeslot',
            name='name_fr',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='address_line1_en',
            field=models.CharField(max_length=45, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='address_line1_fr',
            field=models.CharField(max_length=45, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='address_line2_en',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='address_line2_fr',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='city_en',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='city_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='country_en',
            field=models.CharField(max_length=45, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='country_fr',
            field=models.CharField(max_length=45, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='details_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='details_fr',
            field=models.CharField(max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='name_en',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='name_fr',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='state_province_en',
            field=models.CharField(max_length=55, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='historicalworkplace',
            name='state_province_fr',
            field=models.CharField(max_length=55, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='period',
            name='name_en',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='period',
            name='name_fr',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='picture',
            name='name_en',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='picture',
            name='name_fr',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='name_en',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='name_fr',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='address_line1_en',
            field=models.CharField(max_length=45, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='address_line1_fr',
            field=models.CharField(max_length=45, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='address_line2_en',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='address_line2_fr',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='city_en',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='city_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='country_en',
            field=models.CharField(max_length=45, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='country_fr',
            field=models.CharField(max_length=45, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='details_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='details_fr',
            field=models.CharField(max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='name_en',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='name_fr',
            field=models.CharField(max_length=253, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='state_province_en',
            field=models.CharField(max_length=55, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='state_province_fr',
            field=models.CharField(max_length=55, null=True, verbose_name='State/Province'),
        ),
    ]
