# Generated by Django 2.0.8 on 2018-12-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0020_reservation_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkplace',
            name='place_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Place name'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='place_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Place name'),
        ),
    ]
