# Generated by Django 2.0.8 on 2019-02-20 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workplace', '0021_workplace_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='workplaces', to=settings.AUTH_USER_MODEL, verbose_name='Volunteer'),
        ),
    ]
