# Generated by Django 3.2.8 on 2022-11-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0023_auto_20190517_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreservation',
            name='cancelation_reason',
            field=models.CharField(blank=True, choices=[('U', 'User canceled'), ('TD', 'Timeslot deleted'), ('TM', 'Timeslot modified'), ('A', 'Admin canceled')], max_length=100, null=True, verbose_name='Cancelation reason'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cancelation_reason',
            field=models.CharField(blank=True, choices=[('U', 'User canceled'), ('TD', 'Timeslot deleted'), ('TM', 'Timeslot modified'), ('A', 'Admin canceled')], max_length=100, null=True, verbose_name='Cancelation reason'),
        ),
    ]
