# Generated by Django 3.2.8 on 2023-02-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0024_auto_20221103_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='name',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='name_fr',
        ),
        migrations.DeleteModel(
            name='HistoricalTimeSlot',
        ),
    ]
