# Generated by Django 3.2.8 on 2023-08-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0025_auto_20230203_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkplace',
            name='geolocation_link',
            field=models.TextField(blank=True, null=True, verbose_name='Geolocation link'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='geolocation_link',
            field=models.TextField(blank=True, null=True, verbose_name='Geolocation link'),
        ),
    ]
