# Generated by Django 3.2.8 on 2023-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0026_auto_20230803_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkplace',
            name='is_accessible',
            field=models.BooleanField(default=True, verbose_name='Is accessible'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='is_accessible',
            field=models.BooleanField(default=True, verbose_name='Is accessible'),
        ),
    ]
