# Generated by Django 5.2.12 on 2026-04-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0028_historicalperiod_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalperiod',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Period', 'verbose_name_plural': 'historical Periods'},
        ),
        migrations.AlterModelOptions(
            name='historicalpicture',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Picture', 'verbose_name_plural': 'historical Pictures'},
        ),
        migrations.AlterModelOptions(
            name='historicalreservation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical reservation', 'verbose_name_plural': 'historical reservations'},
        ),
        migrations.AlterModelOptions(
            name='historicalworkplace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Workplace', 'verbose_name_plural': 'historical Workplaces'},
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpicture',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalreservation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalworkplace',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
