# Generated by Django 2.2.7 on 2020-01-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL to execute')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('execution_datetime', models.DateTimeField(verbose_name='Execution datetime')),
                ('execution_interval', models.BigIntegerField(blank=True, null=True, verbose_name='Execution intervals ms')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('executed_at', models.DateTimeField(verbose_name='Executed at')),
                ('success', models.BooleanField(blank=True, default=False, null=True, verbose_name='Succeded ?')),
                ('http_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='HTTP code')),
                ('http_response', models.TextField(blank=True, null=True, verbose_name='HTTP response')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='cron_manager.Task', verbose_name='Task')),
            ],
        ),
    ]
