# Generated by Django 2.0.8 on 2018-12-16 18:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retirement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWaitQueue',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Waiting queue',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWaitQueueNotification',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Wait queue notification',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WaitQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Waiting queue',
                'verbose_name_plural': 'Waiting queues',
            },
        ),
        migrations.CreateModel(
            name='WaitQueueNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wait queue notification',
                'verbose_name_plural': 'Wait queue notification',
            },
        ),
        migrations.AddField(
            model_name='historicalretirement',
            name='next_user_notified',
            field=models.PositiveIntegerField(default=0, verbose_name='Index of the user to be notified next for a resserved place.'),
        ),
        migrations.AddField(
            model_name='historicalretirement',
            name='notification_interval',
            field=models.DurationField(default=datetime.timedelta(1), verbose_name='Time between two reserved place notifications.'),
        ),
        migrations.AddField(
            model_name='historicalretirement',
            name='reserved_seats',
            field=models.IntegerField(default=0, verbose_name='Reserved seats'),
        ),
        migrations.AddField(
            model_name='retirement',
            name='next_user_notified',
            field=models.PositiveIntegerField(default=0, verbose_name='Index of the user to be notified next for a resserved place.'),
        ),
        migrations.AddField(
            model_name='retirement',
            name='notification_interval',
            field=models.DurationField(default=datetime.timedelta(1), verbose_name='Time between two reserved place notifications.'),
        ),
        migrations.AddField(
            model_name='retirement',
            name='reserved_seats',
            field=models.IntegerField(default=0, verbose_name='Reserved seats'),
        ),
        migrations.AddField(
            model_name='waitqueuenotification',
            name='retirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wait_queue_notifications', to='retirement.Retirement', verbose_name='Retirement'),
        ),
        migrations.AddField(
            model_name='waitqueuenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wait_queue_notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='waitqueue',
            name='retirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wait_queue', to='retirement.Retirement', verbose_name='Retirement'),
        ),
        migrations.AddField(
            model_name='waitqueue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wait_queues', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='historicalwaitqueuenotification',
            name='retirement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='retirement.Retirement'),
        ),
        migrations.AddField(
            model_name='historicalwaitqueuenotification',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalwaitqueue',
            name='retirement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='retirement.Retirement'),
        ),
        migrations.AddField(
            model_name='historicalwaitqueue',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='waitqueue',
            unique_together={('user', 'retirement')},
        ),
    ]
