# Generated by Django 2.0.8 on 2018-12-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_custom_payment_reference_number'),
        ('retirement', '0002_wait_queue_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='order_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.OrderLine'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='order_line',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='retirement_reservations', to='store.OrderLine', verbose_name='Order line'),
            preserve_default=False,
        ),
    ]
