# Generated by Django 2.0.8 on 2018-12-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0003_reservation_order_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretirement',
            name='accessibility',
            field=models.BooleanField(default=True, verbose_name='Accessibility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalretirement',
            name='form_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Form URL'),
        ),
        migrations.AddField(
            model_name='retirement',
            name='accessibility',
            field=models.BooleanField(default=1, verbose_name='Accessibility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retirement',
            name='form_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Form URL'),
        ),
    ]
