# Generated by Django 2.0.8 on 2019-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0006_auto_20190115_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='refundable',
            field=models.BooleanField(default=True, verbose_name='Refundable'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refundable',
            field=models.BooleanField(default=True, verbose_name='Refundable'),
        ),
    ]
