# Generated by Django 2.0.8 on 2019-03-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0008_reservations_exchangeable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='order_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retirement_reservations', to='store.OrderLine', verbose_name='Order line'),
        ),
    ]
