# Generated by Django 2.0.8 on 2019-05-17 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0010_auto_20190515_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpicture',
            name='retirement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='retirement.Retirement', verbose_name='Retirement'),
        ),
        migrations.AlterField(
            model_name='historicalreservation',
            name='order_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.OrderLine', verbose_name='Order line'),
        ),
        migrations.AlterField(
            model_name='historicalreservation',
            name='retirement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='retirement.Retirement', verbose_name='Retirement'),
        ),
        migrations.AlterField(
            model_name='historicalreservation',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalwaitqueue',
            name='retirement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='retirement.Retirement', verbose_name='Retirement'),
        ),
        migrations.AlterField(
            model_name='historicalwaitqueue',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalwaitqueuenotification',
            name='retirement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='retirement.Retirement', verbose_name='Retirement'),
        ),
        migrations.AlterField(
            model_name='historicalwaitqueuenotification',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
