# Generated by Django 2.0.8 on 2019-05-29 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retirement', '0012_auto_20190529_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalretreat',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Retreat'},
        ),
        migrations.AlterModelOptions(
            name='retreat',
            options={'verbose_name': 'Retreat', 'verbose_name_plural': 'Retreats'},
        ),
        migrations.RenameField(
            model_name='historicalpicture',
            old_name='retirement',
            new_name='retreat',
        ),
        migrations.RenameField(
            model_name='historicalreservation',
            old_name='retirement',
            new_name='retreat',
        ),
        migrations.RenameField(
            model_name='historicalwaitqueue',
            old_name='retirement',
            new_name='retreat',
        ),
        migrations.RenameField(
            model_name='historicalwaitqueuenotification',
            old_name='retirement',
            new_name='retreat',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='retirement',
            new_name='retreat',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='retirement',
            new_name='retreat',
        ),
        migrations.RenameField(
            model_name='waitqueuenotification',
            old_name='retirement',
            new_name='retreat',
        ),
        migrations.RenameField(
            model_name='waitqueue',
            old_name='retirement',
            new_name='retreat',
        ),
        migrations.AlterField(
            model_name='historicalpicture',
            name='retreat',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='+', to='retirement.Retreat',
                                    verbose_name='Retreat'),
        ),
        migrations.AlterField(
            model_name='historicalreservation',
            name='cancelation_reason',
            field=models.CharField(blank=True, choices=[('U', 'User canceled'),
                                                        ('RD',
                                                         'Retreat deleted'), (
                                                        'RM',
                                                        'Retreat modified')],
                                   max_length=100, null=True,
                                   verbose_name='Cancelation reason'),
        ),
        migrations.AlterField(
            model_name='historicalreservation',
            name='retreat',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='+', to='retirement.Retreat',
                                    verbose_name='Retreat'),
        ),
        migrations.AlterField(
            model_name='historicalwaitqueue',
            name='retreat',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='+', to='retirement.Retreat',
                                    verbose_name='Retreat'),
        ),
        migrations.AlterField(
            model_name='historicalwaitqueuenotification',
            name='retreat',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='+', to='retirement.Retreat',
                                    verbose_name='Retreat'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='retreats',
                                    verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='retreat',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='pictures',
                                    to='retirement.Retreat',
                                    verbose_name='Retreat'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cancelation_reason',
            field=models.CharField(blank=True, choices=[('U', 'User canceled'),
                                                        ('RD',
                                                         'Retreat deleted'), (
                                                        'RM',
                                                        'Retreat modified')],
                                   max_length=100, null=True,
                                   verbose_name='Cancelation reason'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='order_line',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='retreat_reservations',
                                    to='store.OrderLine',
                                    verbose_name='Order line'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='retreat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reservations', to='retirement.Retreat',
                verbose_name='Retreat'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='retreat_reservations',
                to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='exclusive_memberships',
            field=models.ManyToManyField(blank=True, related_name='retreats',
                                         to='store.Membership',
                                         verbose_name='Memberships'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='retreats',
                                         through='retirement.Reservation',
                                         to=settings.AUTH_USER_MODEL,
                                         verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='waitqueue',
            name='retreat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wait_queue', to='retirement.Retreat',
                verbose_name='Retreat'),
        ),
        migrations.AlterField(
            model_name='waitqueuenotification',
            name='retreat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wait_queue_notifications',
                to='retirement.Retreat', verbose_name='Retreat'),
        ),
    ]
