# Generated by Django 2.0.8 on 2019-07-30 13:10

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


def update_inscription_date(apps, schema_editor):
    reservation_model = apps.get_model('retirement', 'reservation')
    for reservation in reservation_model.objects.all():
        if reservation.order_line:
            reservation.inscription_date = reservation.order_line.order.transaction_date
        else:
            reservation.inscription_date = reservation.retreat.start_time

        reservation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0013_auto_20190529_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='inscription_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 30, 13, 10, 22, 589179, tzinfo=utc), editable=False, verbose_name='Inscription date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='inscription_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Inscription date'),
            preserve_default=False,
        ),
        migrations.RunPython(update_inscription_date),
    ]
