# Generated by Django 2.2.2 on 2019-08-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0014_auto_20190730_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreat',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='details',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='details_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='details_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='details',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='details_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='details_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details'),
        ),
    ]
