# Generated by Django 2.2.5 on 2019-09-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0017_auto_20190901_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreat',
            name='accessibility_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Accessibility Detail'),
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='food_allergen_free',
            field=models.BooleanField(default=False, verbose_name='Food allergen_free'),
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='food_gluten_free',
            field=models.BooleanField(default=False, verbose_name='Food gluten free'),
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='food_vegan',
            field=models.BooleanField(default=False, verbose_name='Food vegan'),
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='food_vege',
            field=models.BooleanField(default=False, verbose_name='Food vege'),
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='google_maps_url',
            field=models.TextField(blank=True, null=True, verbose_name='Google maps URL'),
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='sub_title',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Title'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='accessibility_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Accessibility Detail'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='food_allergen_free',
            field=models.BooleanField(default=False, verbose_name='Food allergen_free'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='food_gluten_free',
            field=models.BooleanField(default=False, verbose_name='Food gluten free'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='food_vegan',
            field=models.BooleanField(default=False, verbose_name='Food vegan'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='food_vege',
            field=models.BooleanField(default=False, verbose_name='Food vege'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='google_maps_url',
            field=models.TextField(blank=True, null=True, verbose_name='Google maps URL'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='sub_title',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Title'),
        ),
    ]
