# Generated by Django 2.2.5 on 2019-10-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0018_auto_20190906_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalretreat',
            name='carpool_url',
            field=models.TextField(blank=True, null=True, verbose_name='Carpool URL'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='form_url',
            field=models.TextField(blank=True, null=True, verbose_name='Form URL'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='review_url',
            field=models.TextField(blank=True, null=True, verbose_name='Review URL'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='carpool_url',
            field=models.TextField(blank=True, null=True, verbose_name='Carpool URL'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='form_url',
            field=models.TextField(blank=True, null=True, verbose_name='Form URL'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='review_url',
            field=models.TextField(blank=True, null=True, verbose_name='Review URL'),
        ),
    ]
