# Generated by Django 2.2.5 on 2019-10-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0019_auto_20191001_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreatinvitation',
            name='reserve_seat',
            field=models.BooleanField(default=False, verbose_name='Should reserve seat'),
        ),
        migrations.AddField(
            model_name='retreatinvitation',
            name='reserve_seat',
            field=models.BooleanField(default=False, verbose_name='Should reserve seat'),
        ),
    ]
