# Generated by Django 2.2.6 on 2019-10-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0020_auto_20191004_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreat',
            name='room_type',
            field=models.CharField(blank=True, choices=[('double_occupation', 'Double occupation'), ('single_occupation', 'Single occupation'), ('double_single_occupation', 'Single and double occupation')], max_length=100, null=True, verbose_name='Room Type'),
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='toilet_gendered',
            field=models.BooleanField(blank=True, null=True, verbose_name='gendered toilet'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='room_type',
            field=models.CharField(blank=True, choices=[('double_occupation', 'Double occupation'), ('single_occupation', 'Single occupation'), ('double_single_occupation', 'Single and double occupation')], max_length=100, null=True, verbose_name='Room Type'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='toilet_gendered',
            field=models.BooleanField(blank=True, null=True, verbose_name='gendered toilet'),
        ),
    ]
