# Generated by Django 2.2.6 on 2019-11-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0021_auto_20191010_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retreat_reservations', to='store.OrderLine', verbose_name='Order line'),
        ),
    ]
