# Generated by Django 2.2.8 on 2020-01-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0023_auto_20191222_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwaitqueue',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Used'),
        ),
        migrations.AddField(
            model_name='waitqueue',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Used'),
        ),
        migrations.AddField(
            model_name='waitqueueplacereserved',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Used'),
        ),
    ]
