# Generated by Django 2.2.10 on 2020-03-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0024_auto_20200123_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='post_event_send',
            field=models.BooleanField(default=False, verbose_name='Post event notification send'),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='pre_event_send',
            field=models.BooleanField(default=False, verbose_name='Pre event notification send'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='post_event_send',
            field=models.BooleanField(default=False, verbose_name='Post event notification send'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pre_event_send',
            field=models.BooleanField(default=False, verbose_name='Pre event notification send'),
        ),
    ]
