# Generated by Django 2.2.12 on 2020-05-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0026_auto_20200403_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreat',
            name='type',
            field=models.CharField(choices=[('V', 'Virtual'), ('P', 'Physical')], default='P', max_length=100, verbose_name='Type of retreat'),
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='videoconference_link',
            field=models.TextField(blank=True, null=True, verbose_name='Videoconference link'),
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='videoconference_tool',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Videoconference tool'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='type',
            field=models.CharField(choices=[('V', 'Virtual'), ('P', 'Physical')], default='P', max_length=100, verbose_name='Type of retreat'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='videoconference_link',
            field=models.TextField(blank=True, null=True, verbose_name='Videoconference link'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='videoconference_tool',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Videoconference tool'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='accessibility',
            field=models.BooleanField(blank=True, null=True, verbose_name='Accessibility'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='has_shared_rooms',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='place_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Place name'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='accessibility',
            field=models.BooleanField(blank=True, null=True, verbose_name='Accessibility'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='has_shared_rooms',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='place_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Place name'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code'),
        ),
    ]
