# Generated by Django 2.2.12 on 2020-06-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0027_auto_20200526_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalretreat',
            name='address_line1',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='address_line1_en',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='address_line1_fr',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='city_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='city_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='country',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='country_en',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='country_fr',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='old_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id before migrate to base product'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='state_province',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='state_province_en',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='state_province_fr',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='address_line1',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='address_line1_en',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='address_line1_fr',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='city_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='city_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='country',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='country_en',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='country_fr',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='old_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id before migrate to base product'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='state_province',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='state_province_en',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='state_province_fr',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='State/Province'),
        ),
    ]
