# Generated by Django 2.2.12 on 2020-07-20 15:17

from django.db import migrations, models
import django.db.models.deletion


def migrate_type_of_retreat(apps, schema_editor):
    Retreat = apps.get_model('retirement', 'Retreat')
    RetreatType = apps.get_model('retirement', 'RetreatType')

    physical, created = RetreatType.objects.get_or_create(
        name_fr='Physique',
        name_en='Physical',
        minutes_before_display_link=0
    )

    virtual, created = RetreatType.objects.get_or_create(
        name_fr='Virtuelle',
        name_en='Virtual',
        minutes_before_display_link=30
    )

    for retreat in Retreat.objects.all():
        if retreat.type == 'V':
            retreat.type_new = virtual
        if retreat.type == 'P':
            retreat.type_new = physical

        retreat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('retirement', '0029_auto_20200720_1127'),
    ]

    operations = [
        migrations.RunPython(migrate_type_of_retreat),
    ]
