# Generated by Django 2.2.12 on 2020-07-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0030_migration_of_retreat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalretreat',
            name='type',
        ),
        migrations.RemoveField(
            model_name='retreat',
            name='type',
        ),
    ]
