# Generated by Django 2.2.12 on 2020-07-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0031_auto_20200720_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalretreat',
            old_name='type_new',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='retreat',
            name='type_new',
        ),
        migrations.AddField(
            model_name='retreat',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retreats', to='retirement.RetreatType'),
        ),
    ]
