# Generated by Django 2.2.12 on 2020-07-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0032_auto_20200720_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreat',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='retreats', to='retirement.RetreatType'),
            preserve_default=False,
        ),
    ]
