# Generated by Django 2.2.12 on 2020-07-20 17:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retirement', '0033_auto_20200720_1202'),
    ]

    operations = []
