# Generated by Django 2.2.12 on 2020-07-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0034_auto_20200720_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreattype',
            name='number_of_tomatoes',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of tomatoes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retreattype',
            name='number_of_tomatoes',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of tomatoes'),
            preserve_default=False,
        ),
    ]
