# Generated by Django 2.2.12 on 2020-07-23 18:03

from django.db import migrations


def migrate_retreat_date_intervals(apps, schema_editor):
    Retreat = apps.get_model('retirement', 'Retreat')
    RetreatDate = apps.get_model('retirement', 'RetreatDate')

    for retreat in Retreat.objects.all():
        RetreatDate.objects.create(
            retreat=retreat,
            start_time=retreat.start_time,
            end_time=retreat.end_time,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0038_retreatdate'),
    ]

    operations = [
        migrations.RunPython(migrate_retreat_date_intervals),
    ]
