# Generated by Django 2.2.12 on 2020-07-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0039_auto_20200723_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalretreat',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='historicalretreat',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='retreat',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='retreat',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
