# Generated by Django 2.2.12 on 2020-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0041_auto_20200813_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreattype',
            name='icon',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='retreattype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='retreat-type-icon', verbose_name='icon'),
        ),
    ]
