# Generated by Django 2.2.12 on 2020-08-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0042_auto_20200813_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreattype',
            name='is_virtual',
            field=models.BooleanField(default=False, verbose_name='Is virtual'),
        ),
        migrations.AddField(
            model_name='retreattype',
            name='is_virtual',
            field=models.BooleanField(default=False, verbose_name='Is virtual'),
        ),
    ]
