# Generated by Django 2.2.12 on 2020-08-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0044_auto_20200813_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalretreat',
            name='min_day_exchange',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum days before the event for exchange'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='min_day_refund',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum days before the event for refund'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='refund_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Refund rate'),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Seats'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='min_day_exchange',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum days before the event for exchange'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='min_day_refund',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum days before the event for refund'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='refund_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Refund rate'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Seats'),
        ),
    ]
