# Generated by Django 2.2.12 on 2020-08-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0045_auto_20200813_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalretreat',
            name='seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Seats'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Seats'),
        ),
    ]
