# Generated by Django 2.2.12 on 2020-08-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0046_auto_20200813_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retreatdate',
            options={'ordering': ['start_time'], 'verbose_name': 'Retreat date', 'verbose_name_plural': 'Retreat dates'},
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='animator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='animator'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='animator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='animator'),
        ),
    ]
