# Generated by Django 2.2.12 on 2020-08-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0047_auto_20200814_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalretreattype',
            name='average_duration_in_minute',
        ),
        migrations.RemoveField(
            model_name='retreattype',
            name='average_duration_in_minute',
        ),
        migrations.AddField(
            model_name='historicalretreattype',
            name='duration_description',
            field=models.TextField(default='placeholder', verbose_name='Description of duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retreattype',
            name='duration_description',
            field=models.TextField(default='placeholder', verbose_name='Description of duration'),
            preserve_default=False,
        ),
    ]
