# Generated by Django 2.2.12 on 2020-08-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0049_auto_20200814_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retreattype',
            options={'ordering': ['index_ordering'], 'verbose_name': 'Type of retreat', 'verbose_name_plural': 'Types of retreat'},
        ),
    ]
