# Generated by Django 2.2.12 on 2020-08-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0050_auto_20200814_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreattype',
            name='cancellation_policies',
            field=models.TextField(default='placeholder', verbose_name='Cancellation policies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retreattype',
            name='cancellation_policies',
            field=models.TextField(default='placeholder', verbose_name='Cancellation policies'),
            preserve_default=False,
        ),
    ]
