# Generated by Django 2.2.12 on 2020-08-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0052_auto_20200814_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalretreattype',
            name='know_more_link',
            field=models.TextField(blank=True, null=True, verbose_name='Know more link'),
        ),
        migrations.AlterField(
            model_name='retreattype',
            name='know_more_link',
            field=models.TextField(blank=True, null=True, verbose_name='Know more link'),
        ),
    ]
