# Generated by Django 2.2.12 on 2020-08-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0053_auto_20200814_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreattype',
            name='context_for_welcome_message',
            field=models.TextField(blank=True, default='{}', null=True, verbose_name='Context for welcome message'),
        ),
        migrations.AddField(
            model_name='historicalretreattype',
            name='template_id_for_welcome_message',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Template ID for welcome message'),
        ),
        migrations.AddField(
            model_name='retreattype',
            name='context_for_welcome_message',
            field=models.TextField(blank=True, default='{}', null=True, verbose_name='Context for welcome message'),
        ),
        migrations.AddField(
            model_name='retreattype',
            name='template_id_for_welcome_message',
            field=models.CharField(blank=True, max_length=253, null=True, verbose_name='Template ID for welcome message'),
        ),
    ]
