# Generated by Django 2.2.13 on 2021-05-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0054_auto_20200827_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetreatUsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='retirement.Reservation', verbose_name='Reservation')),
            ],
        ),
    ]
