# Generated by Django 2.2.13 on 2021-05-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0055_retreatusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreat',
            name='display_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='display_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
