# Generated by Django 2.2.13 on 2021-05-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0056_auto_20210519_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreat',
            name='hide_from_client_admin_panel',
            field=models.BooleanField(default=False, verbose_name='Hide from client admin panel'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='hide_from_client_admin_panel',
            field=models.BooleanField(default=False, verbose_name='Hide from client admin panel'),
        ),
    ]
