# Generated by Django 2.2.13 on 2021-06-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0057_auto_20210519_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreat',
            name='number_of_tomatoes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of tomatoes'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='number_of_tomatoes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of tomatoes'),
        ),
    ]
