# Generated by Django 3.2.8 on 2022-01-19 16:24
import datetime

from django.db import migrations


def fill_display_date_on_all_retreat(apps, schema_editor):
    Retreat = apps.get_model('retirement', 'Retreat')

    for retreat in Retreat.objects.all():
        if retreat.display_start_time is None:
            dates = retreat.retreat_dates.all().order_by('start_time')
            if dates.count():
                start_time = dates[0].start_time
            else:
                start_time = datetime.datetime(1990, 1, 1)

            retreat.display_start_time = start_time

        retreat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0058_auto_20210610_1816'),
    ]

    operations = [
        migrations.RunPython(fill_display_date_on_all_retreat),
    ]
