# Generated by Django 3.2.8 on 2022-01-19 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0059_auto_20220119_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalretreat',
            name='display_start_time',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retreat',
            name='display_start_time',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
