# Generated by Django 3.2.8 on 2022-01-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0059_auto_20220119_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalretreat',
            name='display_start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='display_start_time',
            field=models.DateTimeField(),
        ),
    ]
