# Generated by Django 3.2.8 on 2022-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0060_auto_20220119_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreattype',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is visible'),
        ),
        migrations.AddField(
            model_name='retreattype',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is visible'),
        ),
    ]
