# Generated by Django 3.2.8 on 2022-08-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0061_auto_20220319_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreat',
            name='require_purchase_room',
            field=models.BooleanField(default=False, verbose_name='Requires purchase of room option'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='require_purchase_room',
            field=models.BooleanField(default=False, verbose_name='Requires purchase of room option'),
        ),
    ]
