# Generated by Django 4.2.5 on 2025-12-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0065_historicalreservation_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretreat',
            name='waiting_queue_enabled',
            field=models.BooleanField(default=True, verbose_name='Waiting queue enabled'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='waiting_queue_enabled',
            field=models.BooleanField(default=True, verbose_name='Waiting queue enabled'),
        ),
    ]
