# Generated by Django 4.2.5 on 2026-01-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0066_historicalretreat_waiting_queue_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwaitqueue',
            name='new_used_field',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='waitqueue',
            name='new_used_field',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='waitqueueplacereserved',
            name='new_used_field',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
