# Generated by Django 4.2.5 on 2026-01-26 21:08

from django.db import migrations
from django.utils import timezone

def forwards(apps, schema_editor):
    ModelA = apps.get_model("retirement", "WaitQueue")
    ModelB = apps.get_model("retirement", "WaitQueuePlaceReserved")
    now = timezone.now()

    # If old value was True -> set to now, False/NULL -> set to NULL
    ModelA.objects.filter(used=True).update(new_used_field=now)
    ModelB.objects.filter(used=True).update(new_used_field=now)
    ModelA.objects.filter(used=False).update(new_used_field=None)
    ModelB.objects.filter(used=False).update(new_used_field=None)

def backwards(apps, schema_editor):
    ModelA = apps.get_model("retirement", "WaitQueue")
    ModelB = apps.get_model("retirement", "WaitQueuePlaceReserved")

    # Best-effort reverse: any datetime becomes True, NULL becomes False
    ModelA.objects.filter(new_used_field__isnull=False).update(used=True)
    ModelB.objects.filter(new_used_field__isnull=False).update(used=True)
    ModelA.objects.filter(new_used_field__isnull=True).update(used=False)
    ModelB.objects.filter(new_used_field__isnull=True).update(used=False)

class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0067_historicalwaitqueue_new_used_field_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
