# Generated by Django 4.2.5 on 2026-01-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0068_used_boolean_to_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwaitqueue',
            name='used',
        ),
        migrations.RemoveField(
            model_name='waitqueue',
            name='used',
        ),
        migrations.RemoveField(
            model_name='waitqueueplacereserved',
            name='used',
        ),
        migrations.AlterField(
            model_name='historicalwaitqueue',
            name='new_used_field',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Used'),
        ),
        migrations.AlterField(
            model_name='waitqueue',
            name='new_used_field',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Used'),
        ),
        migrations.AlterField(
            model_name='waitqueueplacereserved',
            name='new_used_field',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Used'),
        ),
    ]
