# Generated by Django 4.2.5 on 2026-01-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0069_remove_historicalwaitqueue_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwaitqueue',
            old_name='new_used_field',
            new_name='used',
        ),
        migrations.RenameField(
            model_name='waitqueue',
            old_name='new_used_field',
            new_name='used',
        ),
        migrations.RenameField(
            model_name='waitqueueplacereserved',
            old_name='new_used_field',
            new_name='used',
        ),
    ]
