# Generated by Django 4.2.5 on 2026-01-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0070_rename_new_used_field_historicalwaitqueue_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitqueueplacereserved',
            name='new_notified_field',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Notification date'),
        ),
    ]
