# Generated by Django 4.2.5 on 2026-01-28 15:04

from django.db import migrations
from django.utils import timezone

def forwards(apps, schema_editor):
    Model = apps.get_model("retirement", "WaitQueuePlaceReserved")
    now = timezone.now()

    # If old value was True -> set to now, False/NULL -> set to NULL
    Model.objects.filter(notified=True).update(new_notified_field=now)
    Model.objects.filter(notified=False).update(new_notified_field=None)

def backwards(apps, schema_editor):
    Model = apps.get_model("retirement", "WaitQueuePlaceReserved")

    # Best-effort reverse: any datetime becomes True, NULL becomes False
    Model.objects.filter(new_notified_field__isnull=False).update(notified=True)
    Model.objects.filter(new_notified_field__isnull=True).update(notified=False)
    
class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0071_waitqueueplacereserved_new_notified_field'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
