# Generated by Django 4.2.5 on 2026-01-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0072_notified_boolean_to_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitqueueplacereserved',
            name='notified',
        ),
    ]
