# Generated by Django 4.2.5 on 2026-01-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0073_remove_waitqueueplacereserved_notified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitqueueplacereserved',
            old_name='new_notified_field',
            new_name='notified',
        ),
    ]
