# Generated by Django 5.2.12 on 2026-04-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0074_rename_new_notified_field_waitqueueplacereserved_notified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpicture',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Picture', 'verbose_name_plural': 'historical Pictures'},
        ),
        migrations.AlterModelOptions(
            name='historicalreservation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical reservation', 'verbose_name_plural': 'historical reservations'},
        ),
        migrations.AlterModelOptions(
            name='historicalretreat',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Retreat', 'verbose_name_plural': 'historical Retreats'},
        ),
        migrations.AlterModelOptions(
            name='historicalretreatinvitation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical retreat invitation', 'verbose_name_plural': 'historical retreat invitations'},
        ),
        migrations.AlterModelOptions(
            name='historicalretreattype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Type of retreat', 'verbose_name_plural': 'historical Types of retreat'},
        ),
        migrations.AlterModelOptions(
            name='historicalwaitqueue',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Waiting queue', 'verbose_name_plural': 'historical Waiting queues'},
        ),
        migrations.AlterField(
            model_name='historicalpicture',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalreservation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalretreat',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalretreatinvitation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalretreattype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalwaitqueue',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
