# Generated by Django 5.2.13 on 2026-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0075_alter_historicalpicture_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalretreat',
            name='hide_from_client_admin_panel',
        ),
        migrations.RemoveField(
            model_name='retreat',
            name='hide_from_client_admin_panel',
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled at'),
        ),
        migrations.AddField(
            model_name='historicalretreat',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Is cancelled'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled at'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Is cancelled'),
        ),
    ]
